# Generated by Django 6.0.6 on 2026-07-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_customers_gender'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customers',
            constraint=models.CheckConstraint(condition=models.Q(('age__gte', 18), ('age__lte', 99)), name='age_between_18_and_99'),
        ),
    ]
