# Generated by Django 6.0.6 on 2026-07-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_customers_age_between_18_and_99'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='birth_date',
        ),
    ]
