# Generated by Django 5.0.4 on 2026-06-23 14:01

from django.db import migrations

def set_person_age_group(apps, schema_editor):
    PersonModel = apps.get_model('main_app', 'Person')

    # for p in PersonModel.objects.all():
    #     if p.age < 13:
    #         p.age_group = "Child"
    #     elif p.age < 18:
    #         p.age_group = "Teen"
    #     else:
    #         p.age_group = "Adult"
    #     p.save()

    PersonModel.objects.filter(age__lt=13).update(age_group="Child")
    PersonModel.objects.filter(age__gt=12, age__lt=18).update(age_group="Teen")
    PersonModel.objects.filter(age__gt=17).update(age_group="Adult")


def remove_person_age_group(apps, schema_editor):
    PersonModel = apps.get_model('main_app', 'Person')
    default_age_group = PersonModel._meta.get_field('age_group').default

    # for p in PersonModel.objects.all():
    #     p.age_group = default_age_group
    #     p.save()

    PersonModel.objects.all().filter(age_group=default_age_group)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(code=set_person_age_group, reverse_code=remove_person_age_group),
    ]
