# Generated by Django 5.0.4 on 2026-06-23 14:28

from django.db import migrations

def apply_rarity(apps, schema_editor):
    ItemModel = apps.get_model("main_app", "Item")

    ItemModel.objects.filter(price__lt=11).update(rarity="Rare")
    ItemModel.objects.filter(price__gt=10, price__lt=21).update(rarity="Very Rare")
    ItemModel.objects.filter(price__gt=20, price__lt=31).update(rarity="Extremely Rare")
    ItemModel.objects.filter(price__gt=30).update(rarity="Mega Rare")

def remove_rarity(apps, schema_editor):
    ItemModel = apps.get_model("main_app", "Item")
    default_rarity = ItemModel._meta.get_field("rarity").default

    ItemModel.objects.update(rarity=default_rarity)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.RunPython(apply_rarity, remove_rarity),
    ]
