# Generated by Django 5.0.4 on 2026-06-23 14:40

from django.db import migrations
from django.db.models.functions import Length

from main_app.models import Smartphone


def generate_price(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')

    phones = list(SmartphoneModel.objects.all())

    for phone in phones:
        phone.price = len(phone.brand) * 120

    SmartphoneModel.objects.bulk_update(phones, ['price'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
    ]
