# Generated by Django 5.0.4 on 2026-06-23 16:11

from django.db import migrations
from django.db.models import Model

from main_app.models import Order


def modify_orders_delivery_and_warranty(apps, schema_editor):
    OrderModel = apps.get_model("main_app", "Order")

    for order in OrderModel.objects.all():
        if order.status == Order.Status.PENDING:
            order.delivery = order.order_date + timedelta(days=3)
        elif order.status == Order.Status.COMPLETED:
            order.warranty = "24 months"
        elif order.status == Order.Status.CANCELLED:
            order.delete()
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_order'),
    ]

    operations = [
        migrations.RunPython(modify_orders_delivery_and_warranty),
    ]
